---
title: "regression"
author: "Harrison Cradduck"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE, message=FALSE}
## read in packages
library(tidyverse)
library(dplyr)
library(caret)
library(car)
library(ggfortify)
library(MASS)
library(kableExtra)
library(leaps)
```

```{r}
allPlayersData <- read_csv("allPlayersData.csv")
allPlayersData <- allPlayersData %>%
  mutate(across(everything(), ~ ifelse(is.na(.), 0, .))) %>%
  dplyr::select(-PLAYER_ID)
head(allPlayersData)
colSums(is.na(allPlayersData))
```

```{r}
# glimpse(allPlayersData)
```

```{r}
## run first MLR with all variables
reg1 <- lm(AVG_PLAYING_TIME ~ ., data=allPlayersData)
summary(reg1)
```

```{r}
# vif(reg1)
# alias(reg1)
obs <- allPlayersData$AVG_PLAYING_TIME
pred <- predict(reg1, allPlayersData)
RMSE <- RMSE(pred, obs, na.rm=TRUE)
RMSE
```

```{r}
# null <- lm(AVG_PLAYING_TIME ~ 1, data=allPlayersData)
# forwardAIC <- step(null, direction="forward", scope=list(upper=reg1))
# backwardAIC <- step(reg1, direction="backward")
# n <- dim(allPlayersData)[1]
# forwardBIC <- step(null, direction="forward", scope=list(upper=reg1),k=log(n))
# backwardBIC <- step(reg1, direction="backward",k=log(n))
# stepwiseAIC <- step(null, scope = list(lower = null, upper = reg1), direction = "both")
# stepwiseBIC <- step(null, scope = list(lower = null, upper = reg1), direction = "both", k = log(n))
```

```{r}
extract_stats <- function(model) {
  f_stat <- summary(model)$fstatistic[1]
  rse <- summary(model)$sigma
  r_squared <- summary(model)$r.squared
  adj_r_squared <- summary(model)$adj.r.squared
  rmse <- sqrt(mean(residuals(model)^2))
  return(list(F_stat = f_stat, RSE = rse, R_squared = r_squared, Adj_R_squared = adj_r_squared, RMSE = rmse))
}

stats_forwardAIC <- extract_stats(forwardAIC)
stats_backwardAIC <- extract_stats(backwardAIC)
stats_forwardBIC <- extract_stats(forwardBIC)
stats_backwardBIC <- extract_stats(backwardBIC)
stats_stepwiseAIC <- extract_stats(stepwiseAIC)
stats_stepwiseBIC <- extract_stats(stepwiseBIC)

model_summary <- data.frame(
  Method = c(
    "Forward Elimination (AIC)", 
    "Backward Elimination (AIC)", 
    "Forward Elimination (BIC)", 
    "Backward Elimination (BIC)",
    "Stepwise Elimination (AIC)",
    "Stepwise Elimination (BIC)"
  ),
  # Variables_Selected = c(
  #   paste(names(coef(forwardAIC))[-1], collapse = ", "),
  #   paste(names(coef(backwardAIC))[-1], collapse = ", "),
  #   paste(names(coef(forwardBIC))[-1], collapse = ", "),
  #   paste(names(coef(backwardBIC))[-1], collapse = ", ")
  # ),
  AIC = c(AIC(forwardAIC), AIC(backwardAIC), AIC(forwardBIC), AIC(backwardBIC), AIC(stepwiseAIC), AIC(stepwiseBIC)),
  BIC = c(BIC(forwardAIC), BIC(backwardAIC), BIC(forwardBIC), BIC(backwardBIC), AIC(stepwiseAIC), AIC(stepwiseBIC)),
  RMSE = c(stats_forwardAIC$RMSE, stats_backwardAIC$RMSE, stats_forwardBIC$RMSE, stats_backwardBIC$RMSE, stats_stepwiseAIC$RMSE, stats_stepwiseBIC$RMSE),
  RSE = c(stats_forwardAIC$RSE, stats_backwardAIC$RSE, stats_forwardBIC$RSE, stats_backwardBIC$RSE, stats_stepwiseAIC$RSE, stats_stepwiseBIC$RSE),
  R_squared = c(stats_forwardAIC$R_squared, stats_backwardAIC$R_squared, stats_forwardBIC$R_squared, stats_backwardBIC$R_squared, stats_stepwiseAIC$R_squared, stats_stepwiseBIC$R_squared),
  Adj_R_squared = c(stats_forwardAIC$Adj_R_squared, stats_backwardAIC$Adj_R_squared, stats_forwardBIC$Adj_R_squared, stats_backwardBIC$Adj_R_squared, stats_stepwiseAIC$Adj_R_squared, stats_stepwiseBIC$Adj_R_squared)
)

model_summary %>%
  kable("html", caption = "Summary of Variable Selection Methods and Results") %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  column_spec(2, width = "40em")
```

```{r}
summary(backwardAIC)
```

```{r}
# remove_high_vif_and_insignificant <- function(model, vif_threshold = 3, p_value_threshold = 0.01) {
#   # Step 1: Check for aliasing
#   aliased <- alias(model)$Complete
#   if (nrow(aliased) > 0) {
#     print("Aliased coefficients detected:")
#     print(aliased)
#     # Remove aliased variables
#     model <- update(model, . ~ . - aliased$`(Intercept)`)
#   }
# 
#   # Step 2: Calculate VIFs
#   vif_values <- vif(model)
#   high_vif_vars <- names(vif_values)[vif_values > vif_threshold]
#   
#   if (length(high_vif_vars) > 0) {
#     print(paste("Removing predictors with VIF > ", vif_threshold))
#     print(high_vif_vars)
#     model <- update(model, . ~ . - high_vif_vars)
#   }
# 
#   # Step 3: Check p-values and remove insignificant variables
#   summary_model <- summary(model)
#   p_values <- summary_model$coefficients[, 4]
#   insignificant_vars <- names(p_values)[p_values > p_value_threshold]
#   
#   if (length(insignificant_vars) > 0) {
#     print(paste("Removing predictors with p-value > ", p_value_threshold))
#     print(insignificant_vars)
#     model <- update(model, . ~ . - insignificant_vars)
#   }
#   
#   # Return the final model
#   return(model)
# }
# 
# # Usage
# final_model <- remove_high_vif_and_insignificant(
#   backwardAIC,
#   vif_threshold = 3,
#   p_value_threshold = 0.01
# )
# 
# final_model <- alias(backwardAIC)
```

```{r}
# Removing the insignificant variables (p-value > 0.01) first
significant_model <- lm(AVG_PLAYING_TIME ~ weighted_avg_hit_location_batted +
  weighted_avg_iso_value_batted + weighted_avg_max_times_faced_batted + 
  weighted_avg_max_pitches_thrown_pitched + weighted_avg_release_speed_pitched + 
  weighted_avg_pfx_z_pitched + weighted_avg_vz0_pitched + 
  weighted_avg_delta_run_exp_pitched + total_field_out_batted + 
  total_force_out_batted + total_single_batted + total_strikeout_batted + 
  total_walk_batted + total_at_bats_faced_as_starter_pitched + 
  total_field_out_pitched + total_single_pitched + total_strikeout_pitched + 
  total_walk_pitched + total_pickoff_3b_pitched + 
  total_pickoff_caught_stealing_home_pitched + total_Curveball_pitched + 
  total_Changeup_pitched + `total_Split-Finger_pitched` + total_Forkball_pitched + 
  birthYear + debutYear, data = allPlayersData)

# Calculate VIF for the significant variables
library(car)
vif_values <- vif(significant_model)

# Identify the variables with VIF > 3
high_vif_vars <- names(vif_values)[vif_values > 3]

# Remove high VIF variables
final_model <- update(significant_model, . ~ . - high_vif_vars)

# View the final model summary
summary(final_model)
vif(final_model)
```
```{r}
obs <- allPlayersData$AVG_PLAYING_TIME
pred <- predict(backwardAIC, allPlayersData)
RMSE <- RMSE(pred, obs, na.rm=TRUE)
RMSE
```


